language: swift
osx_image: xcode11.5
xcode_workspace: WaniKaniStatistics.xcworkspace
xcode_scheme: WaniKaniStatistics
before_install:
  - pod repo update
script:
  - xcodebuild -scheme WaniKaniStatistics -workspace WaniKaniStatistics.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
